In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os

In [33]:
import requests
url = 'https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_iris.csv'
response = requests.get(url)
with open('data_iris.csv', 'wb') as file:
    file.write(response.content)
print("File downloaded successfully.")

File downloaded successfully.


In [35]:
df = pd.read_csv('data_iris.csv', header='infer')

In [37]:
df.shape

(150, 5)

In [39]:
df.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [41]:
x = df['Petal.Length']
y = df['Sepal.Length']


In [43]:
np.round(st.pearsonr(x,y),3)

array([0.872, 0.   ])

In [45]:
x.corr(y)

0.8717537758865831

In [ ]:
np.round(df.corr(),3)

In [51]:
np.round(st.spearmanr(x,y),3)

array([0.882, 0.   ])

In [53]:
np.round(st.kendalltau(x,y),3) 

array([0.719, 0.   ])

In [55]:
df = pd.read_csv('data_studentlist.csv', header='infer')

In [57]:
x = df.height
y = df.weight

In [59]:
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [63]:
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': 0.26960396330592223, 'high': 0.8677953581441814}

In [65]:
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': 0.11137578298592947, 'high': 0.9030812794020874}