In [3]:
import numpy as np
np.__version__


'1.26.4'

In [5]:
 arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))
type(arr1)

numpy.ndarray

In [7]:
 arr3 = arr1


In [9]:
 id(arr1)

1823335941968

In [11]:
id(arr3)

1823335941968

In [13]:
arr4 = arr1.copy()


In [15]:
 id(arr4)


1823335940624

In [17]:
 np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [25]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
 np.linspace(1, 10, 5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
 arr = np.linspace(0, 10, 5, retstep=True)
type(arr)

tuple

In [31]:
arr[1]


2.5

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
 np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros(5, dtype ='int64')


array([0, 0, 0, 0, 0], dtype=int64)

In [39]:
 np.zeros(5, dtype ='int64').dtype


dtype('int64')

In [41]:
 arr = np.ones((2,3), dtype ='int_')


In [43]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [47]:
arr.dtype


dtype('int32')

In [49]:
arr.astype('float32')


array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [51]:
arr1 = np.array([111, 2.3, True, False, False])
arr1


array([111. ,   2.3,   1. ,   0. ,   0. ])

In [53]:
 arr3 = np.array([111, True, 'abc'])
arr3

array(['111', 'True', 'abc'], dtype='<U11')

In [55]:
a = np.array([1, 2, 3, 4, 5])
a[2]

3

In [57]:
 a[:]

array([1, 2, 3, 4, 5])

In [59]:
 a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
a[:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
 a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [65]:
 a[1:,1:]

array([[5, 6],
       [8, 9]])

In [67]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 )
arr[arrMask]


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [69]:
 arrMask = ( ( (arr % 5) == 0 ) & ( arr >0) )
arr[arrMask]


array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [71]:
 a.ndim

2

In [73]:
a = np.arange(15)
a.reshape(3,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [77]:
a = a.reshape(3,5)
a


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
a = np.array([2,5,1,3])
a.shape

(4,)

In [81]:
 a = a.reshape((2,2))
a


array([[2, 5],
       [1, 3]])

In [83]:
 a = np.arange(10)
b = a.reshape(2,5)
a[0] = -999


In [85]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [87]:
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [89]:
 a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [91]:
 a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
b


array([[1, 2],
       [3, 4],
       [9, 9]])

In [93]:
 c = np.append(a, [[9], [9]] , axis=1)
c


array([[1, 2, 9],
       [3, 4, 9]])

In [97]:
 a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)


array([2, 3, 4, 5, 6])

In [99]:
np.delete(a, (0, 2, 4))


array([2, 4, 6])

In [101]:
np.delete(a, 0, axis = 0)

array([[4, 5, 6]])

In [103]:
np.delete(a, 1, axis = 1)


array([[1, 3],
       [4, 6]])

In [105]:
import pandas as pd
import numpy as np


In [107]:
 my_index = ['a','b','c']
my_values = [222,333,444]
my_dict = {'a':222, 'b':333, 'c':444}
my_arr = np.array(my_values)


In [109]:
pd.Series(my_values)


0    222
1    333
2    444
dtype: int64

In [111]:
pd.Series(data=my_values, index=my_index)


a    222
b    333
c    444
dtype: int64

In [113]:
pd.Series(my_arr)


0    222
1    333
2    444
dtype: int32

In [115]:
pd.Series(my_arr, index=my_index)

a    222
b    333
c    444
dtype: int32

In [117]:
pd.Series(my_dict)


a    222
b    333
c    444
dtype: int64

In [127]:
s = pd.Series(data=[111,222,333,444], index = ['a','b','c','d'],name='MySeries')
s

a    111
b    222
c    333
d    444
Name: MySeries, dtype: int64

In [129]:
s.index 

Index(['a', 'b', 'c', 'd'], dtype='object')

In [131]:
 s.name 

'MySeries'

In [133]:
 s.values

array([111, 222, 333, 444], dtype=int64)

In [135]:
['a']


['a']

In [137]:
s['a']


111

In [141]:
s1 = pd.Series(data=[1,2,3,4], index = ['d','b','c','a'])
s2 = pd.Series(data=[1,2,3,4], index = ['a','b','d','e'])


In [143]:
s1 + s2


a    5.0
b    4.0
c    NaN
d    4.0
e    NaN
dtype: float64

In [145]:
 2*s1

d    2
b    4
c    6
a    8
dtype: int64

In [147]:
 s1.mean()

2.5

In [149]:
 s1.median()


2.5

In [151]:
 s1.std()


1.2909944487358056

In [153]:
 s1.sort_values()


d    1
b    2
c    3
a    4
dtype: int64

In [155]:
s1.sort_index()


a    4
b    2
c    3
d    1
dtype: int64

In [159]:
 ser_height = pd.Series([165.3, 170.1, 175.0, 182.1, 168.0, 162.0, 155.2, 176.9,178.5, 176.1, 167.1, 180.0, 162.2, 176.1, 158.2, 168.6, 169.2],name='height')
ser_height


0     165.3
1     170.1
2     175.0
3     182.1
4     168.0
5     162.0
6     155.2
7     176.9
8     178.5
9     176.1
10    167.1
11    180.0
12    162.2
13    176.1
14    158.2
15    168.6
16    169.2
Name: height, dtype: float64

In [161]:
 ser_height.apply(lambda x: x/100)

0     1.653
1     1.701
2     1.750
3     1.821
4     1.680
5     1.620
6     1.552
7     1.769
8     1.785
9     1.761
10    1.671
11    1.800
12    1.622
13    1.761
14    1.582
15    1.686
16    1.692
Name: height, dtype: float64

In [163]:
 import pandas as pd
import numpy as np
import os

In [165]:
data = { 'NAME' : ['Jake', 'Jennifer', 'Paul', 'Andrew'], 'AGE': [24,21,25,19],'GENDER':['M','F','M','M']}
df = pd.DataFrame(data)
df

NAME  AGE GENDER
0      Jake   24      M
1  Jennifer   21      F
2      Paul   25      M
3    Andrew   19      M

In [167]:
 df = pd.DataFrame(np.random.rand(10,5), columns=['A','B','C','D','E'])
df.head(3)

A         B         C         D         E
0  0.543535  0.627389  0.981899  0.888499  0.743501
1  0.507078  0.727975  0.290607  0.098047  0.873124
2  0.601234  0.199223  0.047635  0.686195  0.505503